#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &


my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1')
if [[ $my_laptop_external_monitor = *disconnected* ]]; then
    bspc monitor eDP1 -d 1 2 4 6 7 8 9 0
else
    #bspc monitor eDP1 -d 7 8 9 0
    
    bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 0   

fi



bspc config window_gap          10
bspc config top_padding         0
bspc config border_width        3
#bspc config normal_border_color \#E5C07B
#bspc config active_border_color \#E5C07B
bspc config focused_border_color \#ABB2BF
bspc config focus_follows_pointer true
bspc config center_pseudo_tiled true

#dont focus Workspace when spawning window
bspc config ignore_ewmh_focus true

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true  
#bspc config top_monocle_padding  -34


bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop='8' follow=off focus=off
bspc rule -a Thunderbird desktop='8' focus=off follow=off
bspc rule -a freezer desktop='7' focus=off follow=off
bspc rule -a nvim desktop='1' focus=off follow=off
bspc rule -a Blueman-manager desktop='9' focus=off follow=off
bspc rule -a Pavucontrol desktop='9' focus=off follow=off
bspc rule -a update desktop='9' focus=off follow=off
bspc rule -a music desktop='7' focus=off follow=off
bspc rule -a retroarch desktop='6' focus=off follow=off
bspc rule -a firefox:Toolkit state=floating
bspc rule -a "VirtualBox Manager" desktop='9' follow=on
bspc rule -a "VirtualBox Machine" desktop='0' follow=on 



#picom &

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done


#my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1')
#if [[ $my_laptop_external_monitor = *connected* ]]; then
#fi

# launch stuff
# wait for an internet connection
#if wget http://google.com -O- 2>/dev/null; do
sh ~/Scripts/autostartprograms/internet.sh &
# done

#~/Scripts/monitorBspwm
emacs --daemon &
deadd-notification-center &
unclutter &
pavucontrol &
blueman &



xmodmap ~/.config/xkb/Xmodmap &
#autostart Scripts



#"kitty -e tmux "
#export PATH="$PATH:/home/jonas/Scripts/autostartprograms"
#autoNvim.sh &

# Launch bar
.config/polybar/launch.sh --hack 
polybar -q topLaptop -c ~/.config/polybar/hack/config.ini 
